version: "2"

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33061:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - './conf/db/init.sql:/docker-entrypoint-initdb.d/1.sql'
  app:
    links:
      - "database:database"
    build: .
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    environment:
      - APP_ENVIRONMENT=dev
      - CLIENT_HOSTNAME=localhost:4200
      - WEB_CONCURRENCY=2
      - API_SECRET=the_secret   
      - JWT_EXPIRE_IN=3600      
      - DB_USERNAME=user # api account for db
      - DB_PASSWORD=password
      - DB_DB=db
      - DB_URL=database:3306
      # READ FROM LOCAL ENV
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - './app:/app'
    command: ["/start-reload.sh"]
 

volumes: 
  my-db: